load('eegdata.mat');
figure;
plot(eegdata);
title('Original EEG Signal');
xlabel('Time (seconds)');
ylabel('Amplitude');
[coefficients, frequencies] = wavedec(eegdata, 3, 'db4');
reconstructed_signal = waverec(coefficients, frequencies, 'db4');
figure;
subplot(2,1,1);
plot(eegdata);
title('Original EEG Signal');
xlabel('Time (seconds)');
ylabel('Amplitude');
subplot(2,1,2);
plot(reconstructed_signal);
title('Reconstructed EEG Signal');
xlabel('Time (seconds)');
ylabel('Amplitude');
